trying to log error

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -9,11 +9,23 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Install Dependencies if no cache hit
+      - name: Cache node modules
+        uses: actions/cache@v3
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
+      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
+        name: Install Dependencies if no cache hit
         continue-on-error: true
         run: npm ci
       - name: Build Marketplace
-        run: npm run build
+        run: npm run start 2> /tmp/ng-qKL0v8/angular-errors.log
+      - name: Log error details
+        run: cat /tmp/ng-qKL0v8/angular-errors.log || echo "No error log found"
   Unit-Test-Marketplace:
     runs-on: ubuntu-latest
     defaults:
